"""
Holds constants values
"""

BOT_FEE_PER_ADDITIONAL_NAME_MULTIPLIER = 50
BOT_FEE_FOR_NETWORK_ADDRESS_INFO_CHANGE_MULTIPLIER = 20
BOT_REGISTRATION_FEE_MULTIPLIER = 90
BOT_MONTHLY_FEE_MULTIPLIER = 10
