# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.


from .exists_service import ExistsService
from .insert_service import InsertService

from .passthrough_client_jwt import PassThroughClientJwt
from .http_client import HTTPClient


class Client:
    def __init__(self, base_uri=""):
        http_client = HTTPClient(base_uri)
        self.security_schemes = Security(http_client)
        self.exists = ExistsService(http_client)
        self.insert = InsertService(http_client)
        self.close = http_client.close


class Security:
    def __init__(self, http_client):
        self.passthrough_client_jwt = PassThroughClientJwt(http_client)
