# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
from .unhandled_api_error import UnhandledAPIError
from .unmarshall_error import UnmarshallError


class InsertService:
    def __init__(self, client):
        self.client = client

    def insert_put(self, data, headers=None, query_params=None, content_type="application/json"):
        """
        Upload key/value to the remote storage
        It is method for PUT /insert
        """
        uri = self.client.base_url + "/insert"
        return self.client.put(uri, data, headers, query_params, content_type)
