#!/usr/bin/env python3

import os
import sys
from Jumpscale import *

# j.tools.bash.local.locale_check()


import argparse

parser = argparse.ArgumentParser()
parser.add_argument('-q', '--quiet', default=False,
                    action='store_true', help="Turn down logging")
options, args = parser.parse_known_args()


if len(args) == 1:
    if j.sal.fs.exists(args[0]):
        from importlib.machinery import SourceFileLoader
        mymodule = SourceFileLoader('main', args[0]).load_module()
    else:
        toexec = args[0]
        toexec = toexec.strip("'\" ").strip("'\" ")
        exec(toexec)
else:
    j.shell(loc=False)

