#!/usr/bin/env python3

import os
import sys
from Jumpscale import j
# from gevent import monkey
# monkey.patch_all()

# j.tools.bash.local.locale_check()


import argparse

parser = argparse.ArgumentParser()
parser.add_argument('-q', '--quiet', default=False,
                    action='store_true', help="Turn down logging")
options, args = parser.parse_known_args()


if len(args) == 1:
    if j.sal.fs.exists(args[0]):
        from importlib.machinery import SourceFileLoader
        mymodule = SourceFileLoader('main', args[0]).load_module()
    else:
        toexec = args[0]
        toexec = toexec.strip("'\" ").strip("'\" ")
        exec(toexec,globals(),j._locals_get({}))
else:
    j.data.bcdb #needed to make sure we have bcdb running, needed for code completion
    j.shell(loc=False,locals_=locals(),globals_=globals())

