# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
from Jumpscale import j

from .api_service import ApiService

from .http_client import HTTPClient

JSBASE = j.application.JSBaseClass
JSConfigClient = j.application.JSBaseClass
JSConfigFactory = j.application.JSFactoryBaseClass
TEMPLATE =  """
base_uri = "https://capacity.threefoldtoken.com"
"""


class Client(JSConfigClient):

    def __init__(self, instance, data={}, parent=None, interactive=False):
        super().__init__(instance=instance, data=data, parent=parent, template=TEMPLATE, interactive=interactive)
        http_client = HTTPClient(self.config.data['base_uri'])
        self.api = ApiService(http_client)
        self.close = http_client.close


class GridCapacityFactory(JSConfigFactory):

    def __init__(self):
        self.__jslocation__ = "j.clients.threefold_directory"
        self.connections = {}
        self._api = None
        JSConfigFactory.__init__(self, Client)

    @property
    def client(self):
        if self._api is None:
            self.configure(instance="main")
            self._api =  self.get().api
        return self._api

    @property
    def _capacity(self):
        def do():
            return [item for item in self.client.ListCapacity()[0]]
        return self._cache.get("_capacity", method=do, expire=600)

    @property
    def _farmers(self):
        def do():
            return [item for item in self.client.ListFarmers()[0]]
        return self._cache.get("_farmers", method=do, expire=600)

    @property
    def capacity(self):
        """
        is cached for 60 sec
        """
        return [item.as_dict() for item in self._capacity]



    @property
    def farmers(self):
        """
        is cached for 60 sec
        """
        return [item.as_dict() for item in self._farmers]

    def configure(self, instance, base_uri="https://capacity.threefoldtoken.com", interactive=False):
        """
        :param base_uri: Url for grid_capacity api
        :type base_uri: str
        """
        data = {}
        data["base_uri"] = base_uri
        return self.get(instance=instance, data=data, interactive=interactive)


    def resource_units(self,reload=False):
        """
        js_shell "print(j.clients.threefold_directory.resource_units())"
        """
        if reload:
            self._cache.reset()
        nodes = self._capacity

        resource_units = {
            'cru': 0,
            'mru': 0,
            'hru': 0,
            'sru': 0,
        }

        for node in nodes:
            resource_units['cru'] += node.total_resources.cru
            resource_units['mru'] += node.total_resources.mru
            resource_units['hru'] += node.total_resources.hru
            resource_units['sru'] += node.total_resources.sru

        return(resource_units)


