# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

"""
Auto-generated class for ResourceUnits
"""

from . import client_support


class ResourceUnits(object):
    """
    auto-generated. don't touch.
    """

    @staticmethod
    def create(**kwargs):
        """
        :type cru: float
        :type hru: float
        :type mru: float
        :type sru: float
        :rtype: ResourceUnits
        """

        return ResourceUnits(**kwargs)

    def __init__(self, json=None, **kwargs):
        if json is None and not kwargs:
            raise ValueError('No data or kwargs present')

        class_name = 'ResourceUnits'
        data = json or kwargs

        # set attributes
        data_types = [float]
        self.cru = client_support.set_property('cru', data, data_types, False, [], False, True, class_name)
        data_types = [float]
        self.hru = client_support.set_property('hru', data, data_types, False, [], False, True, class_name)
        data_types = [float]
        self.mru = client_support.set_property('mru', data, data_types, False, [], False, True, class_name)
        data_types = [float]
        self.sru = client_support.set_property('sru', data, data_types, False, [], False, True, class_name)

    def __str__(self):
        return self.as_json(indent=4)

    def as_json(self, indent=0):
        return client_support.to_json(self, indent=indent)

    def as_dict(self):
        return client_support.to_dict(self)
