# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.


class UnmarshallError(Exception):
    def __init__(self, resp, message=""):
        self.response = resp
        self.message = message
