# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

from enum import Enum


class EnumEditTeamOptionPermission(Enum):
    read = "read"
    write = "write"
    admin = "admin"
