# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

from enum import Enum


class EnumTeamPermission(Enum):
    none = "none"
    read = "read"
    write = "write"
    admin = "admin"
    owner = "owner"
