# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

from enum import Enum


class EnumCreateHookOptionType(Enum):
    gitea = "gitea"
    gogs = "gogs"
    slack = "slack"
    discord = "discord"
