# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

"""
Auto-generated class for PayloadCommitVerification
"""
from six import string_types

from . import client_support


class PayloadCommitVerification(object):
    """
    auto-generated. don't touch.
    """

    @staticmethod
    def create(**kwargs):
        """
        :type payload: string_types
        :type reason: string_types
        :type signature: string_types
        :type verified: bool
        :rtype: PayloadCommitVerification
        """

        return PayloadCommitVerification(**kwargs)

    def __init__(self, json=None, **kwargs):
        pass
        if json is None and not kwargs:
            raise j.exceptions.Value("No data or kwargs present")

        class_name = "PayloadCommitVerification"
        data = json or kwargs

        # set attributes
        data_types = [string_types]
        self.payload = client_support.set_property("payload", data, data_types, False, [], False, False, class_name)
        data_types = [string_types]
        self.reason = client_support.set_property("reason", data, data_types, False, [], False, False, class_name)
        data_types = [string_types]
        self.signature = client_support.set_property("signature", data, data_types, False, [], False, False, class_name)
        data_types = [bool]
        self.verified = client_support.set_property("verified", data, data_types, False, [], False, False, class_name)

    def __str__(self):
        return self.as_json(indent=4)

    def as_json(self, indent=0):
        return client_support.to_json(self, indent=indent)

    def as_dict(self):
        return client_support.to_dict(self)
