# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

"""
Auto-generated class for Team
"""
from .EnumTeamPermission import EnumTeamPermission
from six import string_types

from . import client_support


class Team(object):
    """
    auto-generated. don't touch.
    """

    @staticmethod
    def create(**kwargs):
        """
        :type description: string_types
        :type id: int
        :type name: string_types
        :type permission: EnumTeamPermission
        :rtype: Team
        """

        return Team(**kwargs)

    def __init__(self, json=None, **kwargs):
        pass
        if json is None and not kwargs:
            raise j.exceptions.Value("No data or kwargs present")

        class_name = "Team"
        data = json or kwargs

        # set attributes
        data_types = [string_types]
        self.description = client_support.set_property(
            "description", data, data_types, False, [], False, False, class_name
        )
        data_types = [int]
        self.id = client_support.set_property("id", data, data_types, False, [], False, False, class_name)
        data_types = [string_types]
        self.name = client_support.set_property("name", data, data_types, False, [], False, False, class_name)
        data_types = [EnumTeamPermission]
        self.permission = client_support.set_property(
            "permission", data, data_types, False, [], False, False, class_name
        )

    def __str__(self):
        return self.as_json(indent=4)

    def as_json(self, indent=0):
        return client_support.to_json(self, indent=indent)

    def as_dict(self):
        return client_support.to_dict(self)
